# -*- coding: utf-8 -*-
"""Bai332_Buoi3_Nhom2_CNTT1809.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnXcGJNDJsVnK4qCqVf-KO3jgdoKnx-8

a. Ví dụ minh họa:
viết một hàm Python để tính toán giá trị ⌈n/m⌉ và minh họa bằng cách gán người vào tháng sinh.
"""

import math

def ap_dung_dirichlet_tong_quat(n_chim, m_chuong):
    """
    Tính toán số chim tối thiểu trong một chuồng theo Nguyên lý Dirichlet dạng tổng quát.
    n_chim: số lượng chim bồ câu (ví dụ: số người)
    m_chuong: số lượng chuồng (ví dụ: số tháng trong năm)
    """
    if m_chuong <= 0:
        return "Số chuồng phải lớn hơn 0."

    # Sử dụng math.ceil để làm tròn lên
    so_chim_toi_thieu = math.ceil(n_chim / m_chuong)

    print(f"Có {n_chim} 'chim bồ câu' và {m_chuong} 'chuồng'.")
    print(f"Theo Nguyên lý Dirichlet, ít nhất có một 'chuồng' chứa: {so_chim_toi_thieu} 'chim bồ câu' trở lên.")
    return so_chim_toi_thieu

# Ví dụ 1: 13 người, 12 tháng
print("--- Ví dụ: Sinh nhật theo tháng ---")
ap_dung_dirichlet_tong_quat(13, 12)

# Ví dụ 2: 30 học sinh, 7 ngày trong tuần (sinh nhật trong tuần)
print("\n--- Ví dụ: Sinh nhật theo ngày trong tuần ---")
ap_dung_dirichlet_tong_quat(30, 7)

"""b. Yêu cầu sinh viên sửa và lý giải

•	Một trường học có 400 học sinh. Hãy tính xem chắc chắn có ít nhất bao nhiêu học sinh có cùng ngày sinh trong năm (bỏ qua năm nhuận, coi 1 năm có 365 ngày).

•	Giả sử có 200 chiếc kẹo được chia đều vào 3 cái túi. Hỏi chắc chắn có ít nhất một túi chứa bao nhiêu chiếc kẹo?

•	Gợi ý nâng cao:

o	Bạn có 100 quả bóng được tô 5 màu khác nhau. Hỏi bạn phải lấy ra ít nhất bao nhiêu quả bóng để chắc chắn có ít nhất 20 quả bóng cùng màu? (Đây là bài toán ngược, yêu cầu suy luận ngược từ nguyên lý).

"""

import math

def ap_dung_dirichlet_tong_quat(n_chim, m_chuong):
    """
    Tính toán số chim tối thiểu trong một chuồng theo Nguyên lý Dirichlet dạng tổng quát.
    n_chim: số lượng "chim bồ câu" (ví dụ: học sinh, kẹo, bóng)
    m_chuong: số lượng "chuồng" (ví dụ: ngày sinh, túi, màu)
    """
    if m_chuong <= 0:
        return "Số chuồng phải lớn hơn 0."

    # Sử dụng math.ceil để làm tròn lên
    so_chim_toi_thieu = math.ceil(n_chim / m_chuong)
    return so_chim_toi_thieu


# =================== BÀI TOÁN ===================

# Bài 1: 400 học sinh, 365 ngày trong năm
print("--- Bài 1: 400 học sinh, 365 ngày trong năm ---")
ket_qua1 = ap_dung_dirichlet_tong_quat(400, 365)
print(f"Có 400 học sinh và 365 ngày sinh.")
print(f"=> Theo Nguyên lý Dirichlet, chắc chắn có ít nhất {ket_qua1} học sinh cùng ngày sinh.\n")

# Bài 2: 200 chiếc kẹo chia vào 3 túi
print("--- Bài 2: 200 chiếc kẹo chia vào 3 túi ---")
ket_qua2 = ap_dung_dirichlet_tong_quat(200, 3)
print(f"Có 200 chiếc kẹo và 3 túi.")
print(f"=> Theo Nguyên lý Dirichlet, chắc chắn có ít nhất một túi chứa {ket_qua2} chiếc kẹo.\n")

# Bài 3: 100 quả bóng, 5 màu, cần ít nhất 20 quả cùng màu
print("--- Bài 3: 100 quả bóng, 5 màu ---")
# Trường hợp xấu nhất: mỗi màu chỉ có 19 quả (19*5=95)
# Quả thứ 96 buộc phải làm cho một màu có >=20 quả
ket_qua3 = 95 + 1
print("Trường hợp xấu nhất: lấy 95 quả thì mỗi màu tối đa chỉ có 19 quả, chưa đủ 20.")
print(f"=> Vì vậy phải lấy ít nhất {ket_qua3} quả bóng để chắc chắn có 20 quả cùng màu.")