# -*- coding: utf-8 -*-
"""Bai331_Buoi3_Nhom2_CNTT1809.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvnL3diryuLg-b9lN0pVVPgmz22XcQ-6

a. Ví dụ minh họa
"""

import random

def mo_phong_rut_tat(so_luong_rut):
    """
    Mô phỏng việc rút tất từ ngăn kéo và kiểm tra có đôi tất cùng màu hay không.
    Ngăn kéo có: 5 đôi tất đen (10 chiếc), 5 đôi tất trắng (10 chiếc).
    """
    tat_trong_ngan_keo = ['đen'] * 10 + ['trắng'] * 10

    # Trộn ngẫu nhiên các chiếc tất
    random.shuffle(tat_trong_ngan_keo)

    # Rút ra số lượng tất yêu cầu
    tat_da_rut = tat_trong_ngan_keo[:so_luong_rut]

    # Đếm số lượng tất đen và trắng đã rút được
    dem_den = tat_da_rut.count('đen')
    dem_trang = tat_da_rut.count('trắng')

    print(f"Bạn đã rút ra: {tat_da_rut}")
    print(f"Số tất đen: {dem_den}, Số tất trắng: {dem_trang}")

    # Kiểm tra xem có đôi tất cùng màu hay không (ít nhất 2 chiếc cùng màu)
    if dem_den >= 2 or dem_trang >= 2:
        print("=> CHẮC CHẮN CÓ MỘT ĐÔI TẤT CÙNG MÀU (theo Nguyên lý Dirichlet)!")
        return True
    else:
        print("=> CHƯA CHẮC CHẮN có đôi tất cùng màu.")
        return False

print("--- Mô phỏng rút 2 chiếc tất ---")
mo_phong_rut_tat(2) # Thử chạy vài lần để thấy kết quả có thể chưa chắc chắn

print("\n--- Mô phỏng rút 3 chiếc tất ---")
mo_phong_rut_tat(3) # Thử chạy vài lần, bạn sẽ thấy kết quả luôn là "CHẮC CHẮN CÓ MỘT ĐÔI"
mo_phong_rut_tat(3)
mo_phong_rut_tat(3)

"""b. Yêu cầu sinh viên sửa và lý giải

•	Chạy lại hàm mo_phong_rut_tat(2) nhiều lần. Quan sát và giải thích tại sao đôi khi bạn có đôi tất cùng màu, đôi khi lại không.

•	Điều chỉnh hàm mo_phong_rut_tat để ngăn kéo có thêm 3 đôi tất màu xám (tức là 6 chiếc màu xám). Hỏi bạn cần rút ra bao nhiêu chiếc tất để chắc chắn có một đôi tất cùng màu? Chạy mô phỏng để kiểm chứng.

"""

import random

def mo_phong_rut_tat(so_luong_rut):
    """
    Mô phỏng việc rút tất từ ngăn kéo và kiểm tra có đôi tất cùng màu hay không.
    Ngăn kéo có: 5 đôi tất đen (10 chiếc), 5 đôi tất trắng (10 chiếc), 3 đôi tất xám (6 chiếc).
    """
    tat_trong_ngan_keo = ['đen'] * 10 + ['trắng'] * 10 + ['xám'] * 6

    random.shuffle(tat_trong_ngan_keo)

    tat_da_rut = tat_trong_ngan_keo[:so_luong_rut]

    dem_den = tat_da_rut.count('đen')
    dem_trang = tat_da_rut.count('trắng')
    dem_xam = tat_da_rut.count('xám')

    print(f"Bạn đã rút ra: {tat_da_rut}")
    print(f"Số tất đen: {dem_den}, trắng: {dem_trang}, xám: {dem_xam}")

    # Kiểm tra có đôi tất cùng màu không
    if dem_den >= 2 or dem_trang >= 2 or dem_xam >= 2:
        print("=> CHẮC CHẮN có một đôi tất cùng màu!")
        return True
    else:
        print("=> CHƯA CHẮC CHẮN có đôi tất cùng màu.")
        return False


print("--- Thử rút 3 chiếc ---")
for i in range(5):
    mo_phong_rut_tat(3)

print("\n--- Thử rút 4 chiếc ---")
for i in range(5):
    mo_phong_rut_tat(4)